[package]
name = "day1a"
version = "0.1.0"
authors = ["Warren Hodgkinson <warren.hodgkinson@walmart.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
